name: "✨ Feature Request"
description: Suggest a new idea or improvement
title: "[Feature] - "
labels: [enhancement]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Got an idea to improve ChromEd? Let us know below!
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: What would this feature do? Why is it useful?
      placeholder: It would highlight headings, links, and code blocks when editing `.md` files...
    validations:
      required: true
